-- ============================================================
-- International phone support: full ISO-3166 country seed data,
-- phone length hints per country, and users.phone_e164 columns
-- for canonical E.164 storage independent of the legacy 'phone' field.
-- ============================================================

-- 1) Seed the countries table with all ISO-3166-1 countries.
-- ON CONFLICT (code) DO NOTHING leaves the 4 existing rows (MR, SN, MA, TN,
-- already correctly seeded by migrations 000021/000035) untouched.
INSERT INTO countries (code, name_ar, name_fr, name_en, flag_emoji, country_code, is_active) VALUES
    ('AF', 'أفغانستان', 'Afghanistan', 'Afghanistan', '🇦🇫', '+93', true),
    ('AL', 'ألبانيا', 'Albanie', 'Albania', '🇦🇱', '+355', true),
    ('DZ', 'الجزائر', 'Algérie', 'Algeria', '🇩🇿', '+213', true),
    ('AD', 'أندورا', 'Andorre', 'Andorra', '🇦🇩', '+376', true),
    ('AO', 'أنغولا', 'Angola', 'Angola', '🇦🇴', '+244', true),
    ('AG', 'أنتيغوا وباربودا', 'Antigua-et-Barbuda', 'Antigua and Barbuda', '🇦🇬', '+1268', true),
    ('AR', 'الأرجنتين', 'Argentine', 'Argentina', '🇦🇷', '+54', true),
    ('AM', 'أرمينيا', 'Arménie', 'Armenia', '🇦🇲', '+374', true),
    ('AU', 'أستراليا', 'Australie', 'Australia', '🇦🇺', '+61', true),
    ('AT', 'النمسا', 'Autriche', 'Austria', '🇦🇹', '+43', true),
    ('AZ', 'أذربيجان', 'Azerbaïdjan', 'Azerbaijan', '🇦🇿', '+994', true),
    ('BS', 'باهاماس', 'Bahamas', 'Bahamas', '🇧🇸', '+1242', true),
    ('BH', 'البحرين', 'Bahreïn', 'Bahrain', '🇧🇭', '+973', true),
    ('BD', 'بنغلاديش', 'Bangladesh', 'Bangladesh', '🇧🇩', '+880', true),
    ('BB', 'بربادوس', 'Barbade', 'Barbados', '🇧🇧', '+1246', true),
    ('BY', 'بيلاروسيا', 'Biélorussie', 'Belarus', '🇧🇾', '+375', true),
    ('BE', 'بلجيكا', 'Belgique', 'Belgium', '🇧🇪', '+32', true),
    ('BZ', 'بليز', 'Belize', 'Belize', '🇧🇿', '+501', true),
    ('BJ', 'بنين', 'Bénin', 'Benin', '🇧🇯', '+229', true),
    ('BT', 'بوتان', 'Bhoutan', 'Bhutan', '🇧🇹', '+975', true),
    ('BO', 'بوليفيا', 'Bolivie', 'Bolivia', '🇧🇴', '+591', true),
    ('BA', 'البوسنة والهرسك', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', '🇧🇦', '+387', true),
    ('BW', 'بوتسوانا', 'Botswana', 'Botswana', '🇧🇼', '+267', true),
    ('BR', 'البرازيل', 'Brésil', 'Brazil', '🇧🇷', '+55', true),
    ('BN', 'بروناي', 'Brunei', 'Brunei', '🇧🇳', '+673', true),
    ('BG', 'بلغاريا', 'Bulgarie', 'Bulgaria', '🇧🇬', '+359', true),
    ('BF', 'بوركينا فاسو', 'Burkina Faso', 'Burkina Faso', '🇧🇫', '+226', true),
    ('BI', 'بوروندي', 'Burundi', 'Burundi', '🇧🇮', '+257', true),
    ('CV', 'الرأس الأخضر', 'Cap-Vert', 'Cabo Verde', '🇨🇻', '+238', true),
    ('KH', 'كمبوديا', 'Cambodge', 'Cambodia', '🇰🇭', '+855', true),
    ('CM', 'الكاميرون', 'Cameroun', 'Cameroon', '🇨🇲', '+237', true),
    ('CA', 'كندا', 'Canada', 'Canada', '🇨🇦', NULL, true),
    ('CF', 'جمهورية أفريقيا الوسطى', 'République centrafricaine', 'Central African Republic', '🇨🇫', '+236', true),
    ('TD', 'تشاد', 'Tchad', 'Chad', '🇹🇩', '+235', true),
    ('CL', 'تشيلي', 'Chili', 'Chile', '🇨🇱', '+56', true),
    ('CN', 'الصين', 'Chine', 'China', '🇨🇳', '+86', true),
    ('CO', 'كولومبيا', 'Colombie', 'Colombia', '🇨🇴', '+57', true),
    ('KM', 'جزر القمر', 'Comores', 'Comoros', '🇰🇲', '+269', true),
    ('CG', 'الكونغو', 'Congo', 'Congo', '🇨🇬', '+242', true),
    ('CD', 'جمهورية الكونغو الديمقراطية', 'RD Congo', 'DR Congo', '🇨🇩', '+243', true),
    ('CR', 'كوستاريكا', 'Costa Rica', 'Costa Rica', '🇨🇷', '+506', true),
    ('CI', 'ساحل العاج', 'Côte d''Ivoire', 'Côte d''Ivoire', '🇨🇮', '+225', true),
    ('HR', 'كرواتيا', 'Croatie', 'Croatia', '🇭🇷', '+385', true),
    ('CU', 'كوبا', 'Cuba', 'Cuba', '🇨🇺', '+53', true),
    ('CY', 'قبرص', 'Chypre', 'Cyprus', '🇨🇾', '+357', true),
    ('CZ', 'التشيك', 'Tchéquie', 'Czechia', '🇨🇿', '+420', true),
    ('DK', 'الدنمارك', 'Danemark', 'Denmark', '🇩🇰', '+45', true),
    ('DJ', 'جيبوتي', 'Djibouti', 'Djibouti', '🇩🇯', '+253', true),
    ('DM', 'دومينيكا', 'Dominique', 'Dominica', '🇩🇲', '+1767', true),
    ('DO', 'جمهورية الدومينيكان', 'République dominicaine', 'Dominican Republic', '🇩🇴', '+1809', true),
    ('EC', 'الإكوادور', 'Équateur', 'Ecuador', '🇪🇨', '+593', true),
    ('EG', 'مصر', 'Égypte', 'Egypt', '🇪🇬', '+20', true),
    ('SV', 'السلفادور', 'Salvador', 'El Salvador', '🇸🇻', '+503', true),
    ('GQ', 'غينيا الاستوائية', 'Guinée équatoriale', 'Equatorial Guinea', '🇬🇶', '+240', true),
    ('ER', 'إريتريا', 'Érythrée', 'Eritrea', '🇪🇷', '+291', true),
    ('EE', 'إستونيا', 'Estonie', 'Estonia', '🇪🇪', '+372', true),
    ('SZ', 'إسواتيني', 'Eswatini', 'Eswatini', '🇸🇿', '+268', true),
    ('ET', 'إثيوبيا', 'Éthiopie', 'Ethiopia', '🇪🇹', '+251', true),
    ('FJ', 'فيجي', 'Fidji', 'Fiji', '🇫🇯', '+679', true),
    ('FI', 'فنلندا', 'Finlande', 'Finland', '🇫🇮', '+358', true),
    ('FR', 'فرنسا', 'France', 'France', '🇫🇷', '+33', true),
    ('GA', 'الغابون', 'Gabon', 'Gabon', '🇬🇦', '+241', true),
    ('GM', 'غامبيا', 'Gambie', 'Gambia', '🇬🇲', '+220', true),
    ('GE', 'جورجيا', 'Géorgie', 'Georgia', '🇬🇪', '+995', true),
    ('DE', 'ألمانيا', 'Allemagne', 'Germany', '🇩🇪', '+49', true),
    ('GH', 'غانا', 'Ghana', 'Ghana', '🇬🇭', '+233', true),
    ('GR', 'اليونان', 'Grèce', 'Greece', '🇬🇷', '+30', true),
    ('GD', 'غرينادا', 'Grenade', 'Grenada', '🇬🇩', '+1473', true),
    ('GT', 'غواتيمالا', 'Guatemala', 'Guatemala', '🇬🇹', '+502', true),
    ('GN', 'غينيا', 'Guinée', 'Guinea', '🇬🇳', '+224', true),
    ('GW', 'غينيا بيساو', 'Guinée-Bissau', 'Guinea-Bissau', '🇬🇼', '+245', true),
    ('GY', 'غيانا', 'Guyana', 'Guyana', '🇬🇾', '+592', true),
    ('HT', 'هايتي', 'Haïti', 'Haiti', '🇭🇹', '+509', true),
    ('HN', 'هندوراس', 'Honduras', 'Honduras', '🇭🇳', '+504', true),
    ('HU', 'المجر', 'Hongrie', 'Hungary', '🇭🇺', '+36', true),
    ('IS', 'آيسلندا', 'Islande', 'Iceland', '🇮🇸', '+354', true),
    ('IN', 'الهند', 'Inde', 'India', '🇮🇳', '+91', true),
    ('ID', 'إندونيسيا', 'Indonésie', 'Indonesia', '🇮🇩', '+62', true),
    ('IR', 'إيران', 'Iran', 'Iran', '🇮🇷', '+98', true),
    ('IQ', 'العراق', 'Irak', 'Iraq', '🇮🇶', '+964', true),
    ('IE', 'أيرلندا', 'Irlande', 'Ireland', '🇮🇪', '+353', true),
    ('IL', 'إسرائيل', 'Israël', 'Israel', '🇮🇱', '+972', true),
    ('IT', 'إيطاليا', 'Italie', 'Italy', '🇮🇹', '+39', true),
    ('JM', 'جامايكا', 'Jamaïque', 'Jamaica', '🇯🇲', '+1876', true),
    ('JP', 'اليابان', 'Japon', 'Japan', '🇯🇵', '+81', true),
    ('JO', 'الأردن', 'Jordanie', 'Jordan', '🇯🇴', '+962', true),
    ('KZ', 'كازاخستان', 'Kazakhstan', 'Kazakhstan', '🇰🇿', NULL, true),
    ('KE', 'كينيا', 'Kenya', 'Kenya', '🇰🇪', '+254', true),
    ('KI', 'كيريباتي', 'Kiribati', 'Kiribati', '🇰🇮', '+686', true),
    ('KW', 'الكويت', 'Koweït', 'Kuwait', '🇰🇼', '+965', true),
    ('KG', 'قيرغيزستان', 'Kirghizistan', 'Kyrgyzstan', '🇰🇬', '+996', true),
    ('LA', 'لاوس', 'Laos', 'Laos', '🇱🇦', '+856', true),
    ('LV', 'لاتفيا', 'Lettonie', 'Latvia', '🇱🇻', '+371', true),
    ('LB', 'لبنان', 'Liban', 'Lebanon', '🇱🇧', '+961', true),
    ('LS', 'ليسوتو', 'Lesotho', 'Lesotho', '🇱🇸', '+266', true),
    ('LR', 'ليبيريا', 'Liberia', 'Liberia', '🇱🇷', '+231', true),
    ('LY', 'ليبيا', 'Libye', 'Libya', '🇱🇾', '+218', true),
    ('LI', 'ليختنشتاين', 'Liechtenstein', 'Liechtenstein', '🇱🇮', '+423', true),
    ('LT', 'ليتوانيا', 'Lituanie', 'Lithuania', '🇱🇹', '+370', true),
    ('LU', 'لوكسمبورغ', 'Luxembourg', 'Luxembourg', '🇱🇺', '+352', true),
    ('MG', 'مدغشقر', 'Madagascar', 'Madagascar', '🇲🇬', '+261', true),
    ('MW', 'مالاوي', 'Malawi', 'Malawi', '🇲🇼', '+265', true),
    ('MY', 'ماليزيا', 'Malaisie', 'Malaysia', '🇲🇾', '+60', true),
    ('MV', 'المالديف', 'Maldives', 'Maldives', '🇲🇻', '+960', true),
    ('ML', 'مالي', 'Mali', 'Mali', '🇲🇱', '+223', true),
    ('MT', 'مالطا', 'Malte', 'Malta', '🇲🇹', '+356', true),
    ('MH', 'جزر مارشال', 'Îles Marshall', 'Marshall Islands', '🇲🇭', '+692', true),
    ('MR', 'موريتانيا', 'Mauritanie', 'Mauritania', '🇲🇷', '+222', true),
    ('MU', 'موريشيوس', 'Maurice', 'Mauritius', '🇲🇺', '+230', true),
    ('MX', 'المكسيك', 'Mexique', 'Mexico', '🇲🇽', '+52', true),
    ('FM', 'ميكرونيزيا', 'Micronésie', 'Micronesia', '🇫🇲', '+691', true),
    ('MD', 'مولدوفا', 'Moldavie', 'Moldova', '🇲🇩', '+373', true),
    ('MC', 'موناكو', 'Monaco', 'Monaco', '🇲🇨', '+377', true),
    ('MN', 'منغوليا', 'Mongolie', 'Mongolia', '🇲🇳', '+976', true),
    ('ME', 'الجبل الأسود', 'Monténégro', 'Montenegro', '🇲🇪', '+382', true),
    ('MA', 'المغرب', 'Maroc', 'Morocco', '🇲🇦', '+212', true),
    ('MZ', 'موزمبيق', 'Mozambique', 'Mozambique', '🇲🇿', '+258', true),
    ('MM', 'ميانمار', 'Myanmar', 'Myanmar', '🇲🇲', '+95', true),
    ('NA', 'ناميبيا', 'Namibie', 'Namibia', '🇳🇦', '+264', true),
    ('NR', 'ناورو', 'Nauru', 'Nauru', '🇳🇷', '+674', true),
    ('NP', 'نيبال', 'Népal', 'Nepal', '🇳🇵', '+977', true),
    ('NL', 'هولندا', 'Pays-Bas', 'Netherlands', '🇳🇱', '+31', true),
    ('NZ', 'نيوزيلندا', 'Nouvelle-Zélande', 'New Zealand', '🇳🇿', '+64', true),
    ('NI', 'نيكاراغوا', 'Nicaragua', 'Nicaragua', '🇳🇮', '+505', true),
    ('NE', 'النيجر', 'Niger', 'Niger', '🇳🇪', '+227', true),
    ('NG', 'نيجيريا', 'Nigeria', 'Nigeria', '🇳🇬', '+234', true),
    ('KP', 'كوريا الشمالية', 'Corée du Nord', 'North Korea', '🇰🇵', '+850', true),
    ('MK', 'مقدونيا الشمالية', 'Macédoine du Nord', 'North Macedonia', '🇲🇰', '+389', true),
    ('NO', 'النرويج', 'Norvège', 'Norway', '🇳🇴', '+47', true),
    ('OM', 'عُمان', 'Oman', 'Oman', '🇴🇲', '+968', true),
    ('PK', 'باكستان', 'Pakistan', 'Pakistan', '🇵🇰', '+92', true),
    ('PW', 'بالاو', 'Palaos', 'Palau', '🇵🇼', '+680', true),
    ('PS', 'فلسطين', 'Palestine', 'Palestine', '🇵🇸', '+970', true),
    ('PA', 'بنما', 'Panama', 'Panama', '🇵🇦', '+507', true),
    ('PG', 'بابوا غينيا الجديدة', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', '🇵🇬', '+675', true),
    ('PY', 'باراغواي', 'Paraguay', 'Paraguay', '🇵🇾', '+595', true),
    ('PE', 'بيرو', 'Pérou', 'Peru', '🇵🇪', '+51', true),
    ('PH', 'الفلبين', 'Philippines', 'Philippines', '🇵🇭', '+63', true),
    ('PL', 'بولندا', 'Pologne', 'Poland', '🇵🇱', '+48', true),
    ('PT', 'البرتغال', 'Portugal', 'Portugal', '🇵🇹', '+351', true),
    ('QA', 'قطر', 'Qatar', 'Qatar', '🇶🇦', '+974', true),
    ('RO', 'رومانيا', 'Roumanie', 'Romania', '🇷🇴', '+40', true),
    ('RU', 'روسيا', 'Russie', 'Russia', '🇷🇺', '+7', true),
    ('RW', 'رواندا', 'Rwanda', 'Rwanda', '🇷🇼', '+250', true),
    ('KN', 'سانت كيتس ونيفيس', 'Saint-Christophe-et-Niévès', 'Saint Kitts and Nevis', '🇰🇳', '+1869', true),
    ('LC', 'سانت لوسيا', 'Sainte-Lucie', 'Saint Lucia', '🇱🇨', '+1758', true),
    ('VC', 'سانت فينسنت والغرينادين', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines', '🇻🇨', '+1784', true),
    ('WS', 'ساموا', 'Samoa', 'Samoa', '🇼🇸', '+685', true),
    ('SM', 'سان مارينو', 'Saint-Marin', 'San Marino', '🇸🇲', '+378', true),
    ('ST', 'ساو تومي وبرينسيبي', 'Sao Tomé-et-Principe', 'Sao Tome and Principe', '🇸🇹', '+239', true),
    ('SA', 'المملكة العربية السعودية', 'Arabie saoudite', 'Saudi Arabia', '🇸🇦', '+966', true),
    ('SN', 'السنغال', 'Sénégal', 'Senegal', '🇸🇳', '+221', true),
    ('RS', 'صربيا', 'Serbie', 'Serbia', '🇷🇸', '+381', true),
    ('SC', 'سيشيل', 'Seychelles', 'Seychelles', '🇸🇨', '+248', true),
    ('SL', 'سيراليون', 'Sierra Leone', 'Sierra Leone', '🇸🇱', '+232', true),
    ('SG', 'سنغافورة', 'Singapour', 'Singapore', '🇸🇬', '+65', true),
    ('SK', 'سلوفاكيا', 'Slovaquie', 'Slovakia', '🇸🇰', '+421', true),
    ('SI', 'سلوفينيا', 'Slovénie', 'Slovenia', '🇸🇮', '+386', true),
    ('SB', 'جزر سليمان', 'Îles Salomon', 'Solomon Islands', '🇸🇧', '+677', true),
    ('SO', 'الصومال', 'Somalie', 'Somalia', '🇸🇴', '+252', true),
    ('ZA', 'جنوب أفريقيا', 'Afrique du Sud', 'South Africa', '🇿🇦', '+27', true),
    ('KR', 'كوريا الجنوبية', 'Corée du Sud', 'South Korea', '🇰🇷', '+82', true),
    ('SS', 'جنوب السودان', 'Soudan du Sud', 'South Sudan', '🇸🇸', '+211', true),
    ('ES', 'إسبانيا', 'Espagne', 'Spain', '🇪🇸', '+34', true),
    ('LK', 'سريلانكا', 'Sri Lanka', 'Sri Lanka', '🇱🇰', '+94', true),
    ('SD', 'السودان', 'Soudan', 'Sudan', '🇸🇩', '+249', true),
    ('SR', 'سورينام', 'Suriname', 'Suriname', '🇸🇷', '+597', true),
    ('SE', 'السويد', 'Suède', 'Sweden', '🇸🇪', '+46', true),
    ('CH', 'سويسرا', 'Suisse', 'Switzerland', '🇨🇭', '+41', true),
    ('SY', 'سوريا', 'Syrie', 'Syria', '🇸🇾', '+963', true),
    ('TW', 'تايوان', 'Taïwan', 'Taiwan', '🇹🇼', '+886', true),
    ('TJ', 'طاجيكستان', 'Tadjikistan', 'Tajikistan', '🇹🇯', '+992', true),
    ('TZ', 'تنزانيا', 'Tanzanie', 'Tanzania', '🇹🇿', '+255', true),
    ('TH', 'تايلاند', 'Thaïlande', 'Thailand', '🇹🇭', '+66', true),
    ('TL', 'تيمور الشرقية', 'Timor oriental', 'Timor-Leste', '🇹🇱', '+670', true),
    ('TG', 'توغو', 'Togo', 'Togo', '🇹🇬', '+228', true),
    ('TO', 'تونغا', 'Tonga', 'Tonga', '🇹🇴', '+676', true),
    ('TT', 'ترينيداد وتوباغو', 'Trinité-et-Tobago', 'Trinidad and Tobago', '🇹🇹', '+1868', true),
    ('TN', 'تونس', 'Tunisie', 'Tunisia', '🇹🇳', '+216', true),
    ('TR', 'تركيا', 'Turquie', 'Turkey', '🇹🇷', '+90', true),
    ('TM', 'تركمانستان', 'Turkménistan', 'Turkmenistan', '🇹🇲', '+993', true),
    ('TV', 'توفالو', 'Tuvalu', 'Tuvalu', '🇹🇻', '+688', true),
    ('UG', 'أوغندا', 'Ouganda', 'Uganda', '🇺🇬', '+256', true),
    ('UA', 'أوكرانيا', 'Ukraine', 'Ukraine', '🇺🇦', '+380', true),
    ('AE', 'الإمارات العربية المتحدة', 'Émirats arabes unis', 'United Arab Emirates', '🇦🇪', '+971', true),
    ('GB', 'المملكة المتحدة', 'Royaume-Uni', 'United Kingdom', '🇬🇧', '+44', true),
    ('US', 'الولايات المتحدة', 'États-Unis', 'United States', '🇺🇸', '+1', true),
    ('UY', 'الأوروغواي', 'Uruguay', 'Uruguay', '🇺🇾', '+598', true),
    ('UZ', 'أوزبكستان', 'Ouzbékistan', 'Uzbekistan', '🇺🇿', '+998', true),
    ('VU', 'فانواتو', 'Vanuatu', 'Vanuatu', '🇻🇺', '+678', true),
    ('VA', 'الفاتيكان', 'Cité du Vatican', 'Vatican City', '🇻🇦', '+379', true),
    ('VE', 'فنزويلا', 'Venezuela', 'Venezuela', '🇻🇪', '+58', true),
    ('VN', 'فيتنام', 'Vietnam', 'Vietnam', '🇻🇳', '+84', true),
    ('YE', 'اليمن', 'Yémen', 'Yemen', '🇾🇪', '+967', true),
    ('ZM', 'زامبيا', 'Zambie', 'Zambia', '🇿🇲', '+260', true),
    ('ZW', 'زيمبابوي', 'Zimbabwe', 'Zimbabwe', '🇿🇼', '+263', true)
ON CONFLICT (code) DO NOTHING;

-- 2) Phone length hints per country (min/max national significant number length,
-- digits only, excluding the dial code). Nullable — used for client-side/server-side
-- soft validation hints only, never enforced as a hard DB constraint (real validation
-- happens via libphonenumber in phone_service.go).
ALTER TABLE countries ADD COLUMN phone_min_length SMALLINT;
ALTER TABLE countries ADD COLUMN phone_max_length SMALLINT;

-- Precise values for the 4 countries already live in production.
UPDATE countries SET phone_min_length = 8, phone_max_length = 8 WHERE code = 'MR';
UPDATE countries SET phone_min_length = 9, phone_max_length = 9 WHERE code = 'SN';
UPDATE countries SET phone_min_length = 9, phone_max_length = 9 WHERE code = 'MA';
UPDATE countries SET phone_min_length = 8, phone_max_length = 8 WHERE code = 'TN';

-- Reasonable common default range (7-12 digits) for every other seeded country,
-- covers the vast majority of real-world national numbering plans without being
-- authoritative -- authoritative validation is done by libphonenumber, not by this hint.
UPDATE countries SET phone_min_length = 7, phone_max_length = 12 WHERE phone_min_length IS NULL;

-- 3) users: canonical E.164 phone + detected ISO region, alongside the legacy
-- 'phone' column (kept as-is, still UNIQUE NOT NULL, never modified by this migration).
ALTER TABLE users ADD COLUMN phone_e164 VARCHAR(20);
ALTER TABLE users ADD COLUMN phone_country_iso VARCHAR(2);

-- Partial unique index: only enforced once a user has been normalized (via Register
-- going forward, or the backfill_phone_e164 one-off tool for existing MR accounts).
CREATE UNIQUE INDEX idx_users_phone_e164_unique ON users(phone_e164) WHERE phone_e164 IS NOT NULL;
